name: Build Website Blocker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: List files for debugging
      run: |
        echo "Files in root directory:"
        dir
        echo "Looking for .csproj files:"
        dir *.csproj

    - name: Restore dependencies
      run: dotnet restore "崔子瑾诱捕器.csproj"

    - name: Build
      run: dotnet build "崔子瑾诱捕器.csproj" --no-restore --configuration Release

    - name: Publish Self-Contained
      run: dotnet publish "崔子瑾诱捕器.csproj" --configuration Release --runtime win-x64 --self-contained true --output "publish/self-contained" -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Publish Framework-Dependent
      run: dotnet publish "崔子瑾诱捕器.csproj" --configuration Release --runtime win-x64 --self-contained false --output "publish/framework-dependent"

    - name: Copy Documentation
      run: |
        copy "README.md" "publish/self-contained/"
        copy "使用说明.md" "publish/self-contained/"
        copy "安装说明.md" "publish/self-contained/"
        copy "README.md" "publish/framework-dependent/"
        copy "使用说明.md" "publish/framework-dependent/"
        copy "安装说明.md" "publish/framework-dependent/"

    - name: Create Self-Contained Archive
      run: |
        Compress-Archive -Path "publish/self-contained/*" -DestinationPath "WebsiteBlocker-v1.0.0-SelfContained.zip"

    - name: Create Framework-Dependent Archive
      run: |
        Compress-Archive -Path "publish/framework-dependent/*" -DestinationPath "WebsiteBlocker-v1.0.0-FrameworkDependent.zip"

    - name: Upload Self-Contained Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WebsiteBlocker-SelfContained
        path: WebsiteBlocker-v1.0.0-SelfContained.zip

    - name: Upload Framework-Dependent Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WebsiteBlocker-FrameworkDependent
        path: WebsiteBlocker-v1.0.0-FrameworkDependent.zip

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          publish/self-contained/
          publish/framework-dependent/
